doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '8.0'
        charset: UTF8
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
          default:
            connection: default
            auto_mapping: true
            naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware